name:                SnowBlock
version:             0.1.0.0
github:              "showrav-ansary/SnowBlock"
license:             BSD3
author:              "A. A. Noman Ansary"
maintainer:          "showrav.ansary.bd@gmail.com"
copyright:           "A. A. Noman Ansary"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/showrav-ansary/SnowBlock#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  SnowBlock-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SnowBlock

tests:
  SnowBlock-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SnowBlock
